### ISSUE TITLE
Review GCIS Resource Conventions

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis-conventions#14]
Doing an initial pass on all our resources.

- [ ] GCIS Defaults - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/Defaults.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/32) activity - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/activity.md)
- [ ] [D](https://github.com/USGCRP/gcis-conventions/issues/36) Array - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/array.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/13) article - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/article.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/20)  book - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/book.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/15) chapter - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/chapter.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/31) contributor - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/contributor.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/17) dataset - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/dataset.md)
- [ ] exterm
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/21) figure - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/figure.md)
- [ ] file
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/23) finding - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/finding.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/25) image - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/image.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/26) journal - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/journal.md)
- [ ] lexicon - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/lexicon.md)
- [x] organization - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/organization.md)
- [x] person - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/person.md)
- [x] publication - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/publication.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/30) reference - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/reference.md)
 - [x] [D](https://github.com/USGCRP/gcis-conventions/issues/35) region - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/region.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/12) report - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/report.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/27) table - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/table.md)
- [x] [D](https://github.com/USGCRP/gcis-conventions/issues/18) web_page - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/web_page.md)

[Meta Level Convo](https://github.com/USGCRP/gcis-conventions/issues/24)

- [x] platform - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/platform.md)
- [x] instrument - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/instrument.md)
- [x] instrument_instance - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/instrument_instance.md)
- [x] model - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/model.md)
- [x] project - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/project.md)
- [x] model_run - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/model_run.md)
- [x] scenario - [Convention Page](https://github.com/USGCRP/gcis-conventions/blob/master/gcis_resources/scenario.md)
